---
- name: Verify inputs
  ansible.builtin.import_tasks: verify.yml

- name: Confirm resource removal
  run_once: true
  when: cx_k8s_app_state == 'absent'
  ansible.builtin.include_tasks: confirm_absent.yml

- name: Kubernetes resources
  delegate_to: localhost
  block:
    - name: Create k8s namespace
      when: cx_k8s_app_state == 'present'
      kubernetes.core.k8s:
        context: "{{ cx_k8s_app_k8s_context }}"
        name: "{{ cx_k8s_app_k8s_namespace }}"
        kind: Namespace
        state: present

    - name: Set Helm release to {{ cx_k8s_app_state }}
      when: cx_k8s_app_helm_release | length > 0
      kubernetes.core.helm:
        context: "{{ cx_k8s_app_k8s_context }}"
        name: "{{ cx_k8s_app_helm_release['name'] | default(inventory_hostname_short) }}"
        chart_ref: "{{ cx_k8s_app_helm_release['chart_ref'] }}"
        chart_repo_url: "{{ cx_k8s_app_helm_release['chart_repo_url'] | default(omit) }}"
        chart_version: "{{ cx_k8s_app_helm_release['chart_version'] }}"
        release_namespace: "{{ cx_k8s_app_k8s_namespace }}"
        release_values: "{{ ('values' in cx_k8s_app_helm_release) | ternary(cx_k8s_app_helm_release['values'], omit) }}"
        state: "{{ cx_k8s_app_state }}"

    - name: Set k8s manifests to {{ cx_k8s_app_state }}
      loop: "{{ cx_k8s_app_manifests }}"
      kubernetes.core.k8s:
        context: "{{ cx_k8s_app_k8s_context }}"
        namespace: "{{ cx_k8s_app_k8s_namespace }}"
        src: "{{ item }}"
        state: "{{ cx_k8s_app_state }}"

    - name: Set k8s resources to {{ cx_k8s_app_state }}
      loop: "{{ cx_k8s_app_resources }}"
      loop_control:
        label: "{{ item['kind'] }} {{ item['metadata']['name'] | default(inventory_hostname_short) }}"
      kubernetes.core.k8s:
        apply: true
        context: "{{ cx_k8s_app_k8s_context }}"
        # metadata in resource definition can override 'name' and 'namespace'
        name: "{{ inventory_hostname_short }}"
        namespace: "{{ cx_k8s_app_k8s_namespace }}"
        resource_definition: "{{ item }}"
        state: "{{ cx_k8s_app_state }}"
