---
- name: Verify requirements
  ansible.builtin.assert:
    that:
      - cx_k8s_app_k8s_context | length > 0
      - cx_k8s_app_k8s_namespace | length > 0
      - cx_k8s_app_helm_release | type_debug == 'dict'
      - cx_k8s_app_manifests | type_debug == 'list'
      - cx_k8s_app_resources | type_debug == 'list'
      - cx_k8s_app_state in ('present', 'absent')
