---
collections:
  - ansible.posix
  - community.general
  - community.postgresql
  - containers.podman
  # - kubernetes.core
  # TODO: Remove when next release drops
  - name: https://github.com/ansible-collections/kubernetes.core
    type: git
