---
- name: Verify system
  ansible.builtin.assert:
    that:
      - ansible_facts.os_family == 'RedHat'
      - ansible_facts.distribution_major_version in ('9', '10')
      - ansible_facts.virtualization_role in ('host', 'guest')

- name: Upgrade packages
  ansible.builtin.import_tasks: upgrade.yml
- name: Configure ssh
  ansible.builtin.import_tasks: ssh.yml
- name: Configure system
  ansible.builtin.import_tasks: system_base.yml
- name: Configure bare-metal system
  when: ansible_facts.virtualization_role == 'host'
  ansible.builtin.include_tasks: system_host.yml
- name: Configure NVIDIA drivers
  when: cx_base_el_nvidia_version | length > 0
  ansible.builtin.include_tasks: nvidia.yml

- name: Reboot
  when: not cx_base_el_skip_reboot
  ansible.builtin.reboot:
