---
- name: Validate Proxmox VE hosts
  hosts: hosts_pve
  connection: local
  tasks:
    - name: Assert that ansible_user is root
      ansible.builtin.assert:
        that:
          - ansible_user == "root"
    - name: Assert that ansible_host is set correctly
      ansible.builtin.assert:
        that:
          - ansible_host != 'localhost'
          - ansible_host | length > 1

- name: Validate EL hosts
  hosts: hosts_el
  connection: local
  tasks:
    - name: Assert that ansible_user is not root
      ansible.builtin.assert:
        that:
          - ansible_user != "root"
    - name: Assert that ansible_host is set correctly
      ansible.builtin.assert:
        that:
          - ansible_host != 'localhost'
          - ansible_host | length > 1
    - name: Verify cx_base_el role inputs
      ansible.builtin.import_role:
        name: cx_base_el
        tasks_from: verify.yml

- name: Validate k8s apps
  hosts: cx_k8s_app:!cx_k8s_app_cluster
  connection: local
  tasks:
    - name: Determine expected values
      ansible.builtin.set_fact:
        _expected_group: cx_k8s_app_{{ cx_k8s_app_k8s_namespace | replace("-", "_") }}
        _expected_name: "{{ inventory_hostname_short }}.{{ cx_k8s_app_k8s_namespace }}.k8s"
    - name: Assert inventory hostname
      ansible.builtin.assert:
        that:
          - ansible_host == _expected_name
          - inventory_hostname == _expected_name
    - name: Assert grouping by k8s namespace
      ansible.builtin.assert:
        that:
          - inventory_hostname in groups[_expected_group]
    - name: Verify cx_k8s_app role inputs
      ansible.builtin.import_role:
        name: cx_k8s_app
        tasks_from: verify.yml

- name: Validate k8s cluster resources
  hosts: cx_k8s_app_cluster
  connection: local
  tasks:
    - name: Determine expected values
      ansible.builtin.set_fact:
        _expected_name: "{{ inventory_hostname_short }}.k8s"
    - name: Assert inventory hostname
      ansible.builtin.assert:
        that:
          - ansible_host == _expected_name
          - inventory_hostname == _expected_name
    - name: Verify cx_k8s_app role inputs
      ansible.builtin.import_role:
        name: cx_k8s_app
        tasks_from: verify.yml

- name: Validate container apps
  hosts: cx_container_app
  connection: local
  tasks:
    - name: Determine expected values
      ansible.builtin.set_fact:
        _expected_name: "{{ inventory_hostname_short }}.container"
    - name: Assert inventory hostname and target
      ansible.builtin.assert:
        that:
          - ansible_host != _expected_name
          - inventory_hostname == _expected_name
    - name: Verify cx_container_app role inputs
      ansible.builtin.import_role:
        name: cx_container_app
        tasks_from: verify.yml

- name: Validate FortiGate hosts
  hosts: cx_fortigate
  connection: local
  vars:
    ansible_connection: local
  tasks:
    - name: Assert that ansible_host is set correctly
      ansible.builtin.assert:
        that:
          - ansible_host != 'localhost'
          - ansible_host | length > 1
    - name: Assert that API credentials are configured
      ansible.builtin.assert:
        that:
          - ansible_httpapi_session_key is defined
          - ansible_httpapi_session_key is mapping
          - "'access_token' in ansible_httpapi_session_key"
    - name: Verify cx_fortigate role inputs
      ansible.builtin.import_role:
        name: cx_fortigate
        tasks_from: verify.yml
