---
cx_fortigate_vdom: root

cx_fortigate_dhcp_reservations:
  lan1:
    - description: net-dns1
      mac: aa:bb:cc:dd:ee:ff
      ip: 10.80.0.10
  dmz:
    - description: dmz-cam1
      mac: "12:34:56:07:08:09"
      ip: 10.81.0.20

cx_fortigate_sdwan_health_checks:
  - name: CloudflareDNSv4
    server:
      - 1.1.1.1
      - 1.0.0.1
    interval: 1000
    failtime: 5
    recoverytime: 10
    sla:
      - id: 1
        link_cost_factor:
          - latency
          - packet-loss
        latency_threshold: 100
        packetloss_threshold: 2
  - name: CloudflareDNSv6
    addr_mode: ipv6
    server:
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001
    interval: 1000
